### ISSUE TITLE
index.es.css is causing issues with nextjs framework

### ISSUE THREAD

**Issue by surferwat** [GetStream/react-activity-feed#93] opened 2020-03-14 10:14 UTC
Hello! Thanks a lot for writing 'react-activity-feed'. It is very helpful.

Unfortunately, it doesn't seem to be working nicely with my nextjs app. According to the maintainers of nextjs, the issue arises because 'react-activity-feed' imports a CSS file that my app ends up consuming instead of the built package. Please see the error output pasted at the end.

One possible solution that they suggest is for you to publish a compiled version of your dependency, as compiled dependencies do not have references to CSS files, or any other files that require bundler-specific integrations. 

Would it be possible to publish a compiled version? Thank you.

[ error ] /web-app/node_modules/@webscopeio/react-textarea-autocomplete/style.css:1
(function (exports, require, module, __filename, __dirname) { .rta {
                                                              ^
SyntaxError: Unexpected token .
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/w/Desktop/web-app/dyor-1/node_modules/react-activity-feed/dist/index.js:38:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)

**Comment by surferwat** [comment] 2020-03-19 09:32
Hi, just wanted to check in about my issue. Is there somewhere else where I should send my inquiry to? Thanks.

**Comment by agustif** [comment] 2020-04-04 15:18
surfer can you share some codesandbox or somethingg? Im interested on using stream+next too and could try help to debug.

Are you using 9.3.2? Are you adding necessary css loaders etc?

Good luck

**Comment by vishalnarkhede** [comment] 2020-04-04 19:43
Hey @surferwat @agustif I will try to investigate on this next week and get back to you. Sorry for the delays :)

**Comment by agustif** [comment] 2020-04-04 19:54
@vishalnarkhede No probllem thank you.

**Comment by surferwat** [comment] 2020-04-07 11:07
@augustif I am using v.9.3.0. See below for code in my next.config.js. Thanks.

```
const withCSS = require("@zeit/next-css");
const isProd = process.env.NODE_ENV === "production";

if (!isProd) {
  require("dotenv").config();
}

module.exports = withCSS({
  cssModules: true, // Expose module css
  env: {
    HOST: isProd ? process.env.P_HOST : process.env.D_HOST
  }
});
```

@vishalnarkhede Thanks. I'm looking forward to the outcome of your investigation.

**Comment by ilionic** [comment] 2020-04-09 15:50
Experiencing same issue. 
That's due to this direct import 
https://github.com/GetStream/react-activity-feed/blob/b1bd8518f84cb60859fc5a25383012ab94ce1a6c/src/components/Textarea.js#L10

**Comment by surferwat** [comment] 2020-04-10 06:14
@vishalnarkhede any initial feedback on whether it will be possible to fix as suggested by @ilionic ?

I need "load more" functionality, so am wondering whether I should wait or go ahead write my own component for it. Thanks.

**Comment by vishalnarkhede** [comment] 2020-04-10 07:13
@surferwat @ilionic @agustif Fix is on the way! 

Thanks @ilionic for investigation :)

**Comment by vishalnarkhede** [comment] 2020-04-10 07:36
@surferwat @agustif @ilionic  please use `0.10.2`. I have published the fix on this version!

Let me know if it fixes your issue :)

**Comment by surferwat** [comment] 2020-04-10 08:38
@vishalnarkhede thanks for the quick turnaround.

I get the a ReferenceError: document is not defined. See error message below.

[ error ] ReferenceError: document is not defined
    at /web-app/node_modules/blueimp-load-image/js/load-image-orientation.js:47:15
    at /web-app/node_modules/blueimp-load-image/js/load-image-orientation.js:53:5
    at /web-app/node_modules/blueimp-load-image/js/load-image-orientation.js:20:5
    at Object.<anonymous> (/web-app/node_modules/blueimp-load-image/js/load-image-orientation.js:29:3)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/web-app/node_modules/blueimp-load-image/js/index.js:12:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)

**Comment by vishalnarkhede** [comment] 2020-04-10 08:46
@surferwat can you please setup a sample nextjs app where I can see the error? That will help me resolving all the issues faster.

**Comment by surferwat** [comment] 2020-04-10 10:22
@vishalnarkhede Thanks. Are you not getting the same error on your nextjs app?

**Comment by ilionic** [comment] 2020-04-10 11:31
@surferwat re. 
> I get the a ReferenceError: document is not defined. See error message below.

That's due to next.js SSR, you just need to use dynamic import with `ssr: false`

**Comment by surferwat** [comment] 2020-04-10 18:00
@ilionic thanks. That worked like a charm. Although now there is a loading delay between the app nav bar and the feed. I think I like the effect of the entire page loading together offered by ssr.

@vishalnarkhede would it be possible to add a check of some sorts for `document` so that applicable functions don't run unless it is defined?

**Comment by ilionic** [comment] 2020-04-10 19:08
Thanks pretty common use case in next.js world as many libraries are client side only, so you can implement preloader ( actually similar thing I did for Stream Chat ). So asking library for SSR support not always feasible.

**Comment by vishalnarkhede** [comment] 2020-04-13 17:04
@surferwat I haven't yet got chance to test it myself, but from the discussion I can see the cause of issue. We will try to look into it this week and get back to you :)

**Comment by surferwat** [comment] 2020-04-14 14:51
@vishalnarkhede That sounds great. Thanks a lot.

**Comment by surferwat** [comment] 2020-04-21 00:29
@vishalnarkhede Any updates? Thanks.

**Comment by surferwat** [comment] 2020-05-04 00:55
@vishalnarkhede hi, just checking in. Any updates? Thanks.

**Comment by vishalnarkhede** [comment] 2020-05-04 07:08
@surferwat I am really sorry. but I haven't yet managed to look into this yet. I will try to do it this week and get back to you before end of week :)

**Comment by surferwat** [comment] 2020-05-08 07:34
@vishalnarkhede No worries. Thank you for taking a look into this.

**Comment by arnautov-anton** [comment] 2021-05-28 11:21
Hey, @surferwat, just wanted to check in and ask if this is still happening after 1.0.0 update. Let me know so we can close this one or investigate further.

**Comment by surferwat** [comment] 2021-05-29 22:06
Hi @arnautov-anton, I've shutdown the relevant app, so can't say. Thanks for checking in though.

**Comment by arnautov-anton** [comment] 2021-05-31 19:47
Closing for now as theres no `dist/index.es.css` anymore and thus this should not cause any issues anymore. Feel free to @ me so we can reopen this if anything similar pops up.

**Closed by arnautov-anton** 2021-05-31 19:47 UTC
Labels: bug
