### ISSUE TITLE
Dynamically change feed group

### ISSUE THREAD

**Issue by ellioseven** [GetStream/react-activity-feed#263] opened 2021-05-13 05:20 UTC
I'm trying to change the feed group dynamically from a select input inside my `Activity` component. I'm using the `<Feed>` component to build the feed context. No matter what I do, I cannot get the feed activities to change when the dynamic feed group is updated:

```
const Activity = () => {
  const router = useRouter();
  const feedGroup = router.query.id as string;
  return (
    <Feed feedGroup={feedGroup} notify={true}>
      <ActivityFeed />
    </Feed>
  );
};
```

I've tried many things, such as updating the key:

```
<Feed feedGroup={feedGroup} notify={true} key={feedGroup}>
```

this results in:

```
TypeError: Cannot read property 'cancel' of undefined
```

Which seems to happen when the subscription tries to unregister itself from the `useEffect` unmount function. Trying to manually unregister didn't work:

```
const feedContext = useFeedContext();
useEffect(() => {
  feedContext.feedManager.unsubscribe()
}, [feedContext.feedGroup])
```

I've also tried to refresh after the feed group has changed:

```
const feedContext = useFeedContext();
useEffect(() => {
  feedContext.refresh()
}, [feedContext.feedGroup])
```

But this didn't work either. The only thing I can do is `window.location` away to another page, refetching the page and infering the  feed group from the URL. This isn't great as the application has to re-initialise itself. 

Maybe I'm doing something wrong here?

gz#11830

**Comment by arnautov-anton** [comment] 2021-05-19 01:10
Thank you for posting this issue! Sorry for the delay, will take a look ASAP.

**Comment by arnautov-anton** [comment] 2021-05-20 08:35
@ellioseven Bug has been fixed and merged  to `main`, should work fine in the next release. :)

**Comment by mahboubii** [comment] 2021-05-20 12:55
Fixed in v1.1.1

**Closed by mahboubii** 2021-05-20 12:55 UTC
Labels: bug

**Comment by ellioseven** [comment] 2021-05-20 22:59
Beautiful, thanks guys <3

**Comment by ellioseven** [comment] 2021-05-24 02:33
@arnautov-anton I still seem to be hitting this after updating to 1.1.1:

```
TypeError: Cannot read property 'cancel' of undefined
```

This seems to be happening when the component is being unmounted, triggered by a Next.js route change.

I am using the `Feed` and `StreamApp` components in this library.

**Comment by arnautov-anton** [comment] 2021-05-24 10:11
Hey, @ellioseven, that's weird but possible since the fix was tested with CRA. Will do some testing with Next.js and I'll let you know ASAP. Could you also share the whole error that pops up in your implementation please?

**Comment by ellioseven** [comment] 2021-05-25 01:45
![image](https://user-images.githubusercontent.com/4191120/119427511-8025ed00-bd4e-11eb-8c91-5dbe6e47dc85.png)

This seems to be coming from the `unsubscribe` method in `FeedManager.tsx`

**Comment by arnautov-anton** [comment] 2021-05-26 22:28
Hey, @ellioseven! After a long while of testing I still can't seem to reproduce the issue...

Here's the simplest Next.js setup I could come up with to test this thing as close to yours as possible:
![image](https://user-images.githubusercontent.com/43254280/119738422-fb87bb80-be80-11eb-8c93-15b2985dcf06.png)

And here's the result:

https://user-images.githubusercontent.com/43254280/119738688-5f11e900-be81-11eb-8644-9ff01b8496bc.mov

This is pretty serious bug but at this point I can only add optional chaining operator before that pesky `cancel` method to make sure the whole application does not crash but that does not solve the actual problem.
Try and remove/reinstall your `node_modules` and let me know if that helps, this is the only thing that comes to mind right now.

**Comment by ellioseven** [comment] 2021-05-27 00:12
@arnautov-anton

Re-installing didn't fix unfortunately. Seems strange to me as it seems to me that the source actually checks for an undefined subscription, maybe it's an issue with the compiled code? Could be a race condition?

I'll try to get you a reproduceable example as soon as I can. 

Worth noting I'm using the router like so:

```
const router = useRouter();
const filter = router.query.filter as string;

const handleChange = (value: string) => {
  router.push({
    query: {
      // `createFeedGroupKey` formats feed group ID.
      filter: createFeedGroupKey(value)
    }
  });
};

return (
  <>
    <Select>
      <Select.Option value="">All</Select.Option>
      <Select.Option value="my-feed">All</Select.Option>
    </Select>
    <Feed
      feedGroup={filter}
      notify={true}
      options={options}
      userId={streamUserId}
    >
      // ...
    </Feed>
  </>
)
```

**Comment by arnautov-anton** [comment] 2021-05-27 10:10
@ellioseven Is it possible for you to recreate that issue on [codesandbox.io](https://codesandbox.io/)? As for the code snippet you shared; everything seems to be okay. I don't see any issue with the way you're using the router.

**Comment by Rykuno** [comment] 2021-08-05 18:52
> @ellioseven Is it possible for you to recreate that issue on [codesandbox.io](https://codesandbox.io/)? As for the code snippet you shared; everything seems to be okay. I don't see any issue with the way you're using the router.

I'm running into the same issue with my routes such as`/user/[username]`. 

When navigating away from pages it's failing `cancel` on the FeedManager. Quite a bit of work to recreate in a sandbox but i'll give it a shot after work.
